### PR TITLE
Some updates to master branch for liferay 7.0 only

### PR DESCRIPTION
**Pull request by szacchino**
In this fork you'll find:

1) extended support for Language.properties file for english and italian
2) the master branch assetrenderer::getUrlViewInContext() generates URLs of type "/c/find_entry" that required user to login even if it is a guest having view permissions on entities (this happens when searching entities using portal search or an asset publisher); I replaced that code to generate simple renderUrls and added code to check permissions; if the user hasn't permission an exception is thrown. KNOWN TODO: when display entity list in view.jsp, check view permissions and hide entities without view permission for current user;
3) replaced liferay 6.* icons with lexicon ones;
4) replaced - OR - string with liferay localizable message;

### CODE REVIEW

**Comment by yasuflatland-lf** [comment]
@szacchino , thank you for your great contribution! Let me take a look and do some manual testing on my side, then I`ll marge this PR!

**Comment by szacchino** [comment]
I've also coded the view.jsp templates to show only entries with proper permissions. I think i'll commit on monday. Thank you.

**Comment by szacchino** [comment]
I've added also some updates on view.jsp template to show entries only if user has proper permissions.

**Comment by yasuflatland-lf** [comment]
@szacchino Thank you for your contribution!

**Pull request merged**
